version: '3.8'

services:
  api1:
    image: mccutchen/go-httpbin
    #restart: always

  api2:
    image: mccutchen/go-httpbin
    #restart: always

  api3:
    image: mccutchen/go-httpbin
    #restart: always
