version: '3.8'

services:
  api1:
    image: kennethreitz/httpbin
    restart: always

  api2:
    image: kennethreitz/httpbin
    restart: always

  api3:
    image: kennethreitz/httpbin
    restart: always
